App\Entity\Location:
  properties:
    longitude:
      - Range:
          min: -90
          max: 90
          groups: ["edit", "create"]

    latitude:
      - Range:
          min: -180
          max: 180
          groups: [ "edit", "create" ]

App\Entity\Measurement:
  properties:
    celsius:
      - Range:
          min: -40
          max: 45
          groups: ["edit", "create"]
